### ISSUE TITLE
Set warps

### ISSUE THREAD

**Issue by L27SlubbyGames** [AddstarMC/BlockHunt#23]
when I have set my warps and restart (or reload the plugin) my server. and then click on the sign he says that are no warps set for this arena. but in the file is everything good.

**Comment by rt50631** [comment]
Fixed here:
https://github.com/rt50631/BlockHunt/commit/2a0b298c894f912a5e3e523b0dab687869f6fa2b

**Comment by L27SlubbyGames** [comment]
thx!
but can you send me the jar file?

**Comment by Narimm** [comment]
Closed

**Comment by rt50631** [comment]
Here's the jar file:
http://s000.tinyupload.com/index.php?file_id=00810016419868876516

**Comment by L27SlubbyGames** [comment]
sorry to say but it is still broken voor me.

the whole arenas.yml file reset wen I restart my server.

**Comment by rt50631** [comment]
Have you deleted the BlockHunt folder completely and created the arena again?
Are you using my fork?
Everything works fine for me on 1.12 spigot.
